name: Actions Workflow

on: 
  # schedule:
  # Running every minute 0, at 12 hours
  #  - cron: "0 12 * * *"
  push:
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: list files
        run: |
          pwd
          ls -a
      - name: simple js action
        id: greeting
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: "@thiagopaiva99"
      - name: log greeting time
        run: echo "${{ steps.greeting.outputs.time }}"