name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo username
        run: echo "@thiagopaiva99"
      - name: multiline scripts
        run: |
          node -v
          npm -v
      - name: run python commands
        run: |
          import platform
          print(platform.processor())
        shell: python
